name: dev_deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_LOGIN }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest

      - name: executing remote ssh commands restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.LOGIN }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/netomerch-backend/dev
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} > .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo DB_USER=${{ secrets.DB_USER }} >> .env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            echo POSTGRES_USER=${{ secrets.DB_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.DB_PASSOWRD }} >> .env
            echo POSTGRES_DB=${{ secrets.DB_NAME }} >> .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo DEBUG=1 >> .env
            sh down.sh
            docker pull ghcr.io/${{ github.repository }}:latest
            sh up.sh
